[gen-disconnect-called-during-error.https.html]
  [disconnect() called during a getPrimaryServices call that fails. Reject with NetworkError.]
    expected: FAIL

