[collections.py]
  [test_arguments]
    expected: FAIL

