[panner-distance-clamping.html]
  [X new PannerNode(c, {refDistance: -1}) did not throw an exception.]
    expected: FAIL

  [X panner.refDistance = -1 did not throw an exception.]
    expected: FAIL

  [< [ref-distance-error\] 2 out of 6 assertions were failed.]
    expected: FAIL

  [X new PannerNode(c, {maxDistance: -1}) did not throw an exception.]
    expected: FAIL

  [X new PannerNode(c, {maxDistance: 0}) did not throw an exception.]
    expected: FAIL

  [X panner.maxDistance = -1 did not throw an exception.]
    expected: FAIL

  [X panner.maxDistance = 0 did not throw an exception.]
    expected: FAIL

  [< [max-distance-error\] 4 out of 6 assertions were failed.]
    expected: FAIL

  [# AUDIT TASK RUNNER FINISHED: 2 out of 4 tasks were failed.]
    expected: FAIL

